# Generated by Django 4.1 on 2022-09-27 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_tasktodolist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktodolist',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 9, 27, 11, 17, 17, 238359)),
        ),
    ]
