# Generated by Django 4.1 on 2022-09-27 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_alter_tasktodolist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktodolist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 4, 26, 6, 332292, tzinfo=datetime.timezone.utc)),
        ),
    ]
