# Generated by Django 4.1 on 2022-09-28 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_remove_tasktodolist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktodolist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 28, 15, 15, 55, 352262)),
        ),
    ]
