# Generated by Django 4.1 on 2022-09-28 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_alter_tasktodolist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktodolist',
            name='date',
            field=models.DateField(default=datetime.date(2022, 9, 28)),
        ),
    ]
